jenkins:
  systemMessage: "Jenkins настроен через Configuration as Code"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  scriptApproval:
      approvedSignatures:
        - "method org.jenkinsci.plugins.workflow.support.actions.EnvironmentAction getEnvironment"

  # securityRealm:
  #   local:
  #     allowsSignup: false
  #     users:
  #       - id: "admin"
  #         password: "admin-password"

credentials:
  system:
    domainCredentials:
    #   - domain:
    #       name: 'Credentials DWH'
    #       description: 'Credentials for DWH teams'
    #       specifications:
    #         - folderDomainSpecification:
    #             foldefName: 'DWH_GP'
      - credentials:
        - usernamePassword:
            scope: GLOBAL
            id: "cdjksnd"
            username: "cdjks_user"
            password: "jkspass123"
            description: "Учетка для доступа к GitLab"
        - usernamePassword:
            scope: GLOBAL
            id: "adb-prod-admin"
            username: "adb_deploy_cdjks"
            password: "PaswdQ802"
            description: "Учетка для доступа к ADB"
        - usernamePassword:
            scope: GLOBAL
            id: "conflog-prod-admin"
            username: "cdjks_prodlog_deploy"
            password: "password111"
            description: "Учетка для доступа к продлогу"
        - usernamePassword:
            scope: GLOBAL
            id: "conflog-dev-admin"
            username: "cdjks_prodlog_deploy"
            password: "password111"
            description: "Учетка для доступа к девлогу (fake)"
        - usernamePassword:
            scope: GLOBAL
            id: "svc_cdjks_adprod-pass"
            username: "svc_cdjks_adprod"
            password: "password111"
            description: "Доступ к greenplum под gpadmin"
        - usernamePassword:
            scope: GLOBAL
            id: "svc_cdjks_prodlog-pass"
            username: "cdjks_dumper"
            password: "password111"
            description: "Доступ к prodlog для получения дампа"
        - usernamePassword:
            scope: GLOBAL
            id: "ad-afdev01_API"
            username: "svc_cdjks_afapi"
            password: "password111"
            description: "Доступ к Airflow API"

jobs:
  - script: |
      folder('DWH_GP') {}
      folder('DWH_GP/internal_manual') {}
      folder('DWH_GP/manual') {}
      folder('DWH_GP/manual/6.ADB_PROD') {}
      folder('DWH_GP/manual/2.Conflog') {}

      pipelineJob('DWH_GP/internal_manual/jks-automatic-all-adb-prod') {
        parameters {
          booleanParam('forceterminate', false, 'Принудительно разорвать все сессии к БД ?')
          booleanParam('hotfix', false, 'Режим Hot Fix?')
          booleanParam('refactoring', false, 'Режим рефакторинг?')
          booleanParam('manualpause', false, 'Ручная пауза дагов')
          booleanParam('doUnpaused', true, 'Снимать даги с паузы после раскатки мастера ? (отключать только в экстренных случаях)')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('pipelines-prod/Jenkinsfile-all-adb-prod')
          }
        }
      }

      pipelineJob('DWH_GP/internal_manual/jks-automatic-deploy-adb-prod') {
        parameters {
          booleanParam('hotfix', false, 'Режим Hot Fix?')
          booleanParam('refactoring', false, 'Режим рефакторинг?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('pipelines-prod/Jenkinsfile-deploy-adb-prod')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/automatic-bdv-v3-adb-prod-META') {
        parameters {
          booleanParam('deployDags', true, 'Задеплоить даги на AF prod')
          booleanParam('unpauseDags', false, 'Снимать даги с паузы после деплоя?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('pipelines-prod/Jenkinsfile-automatic-bdv-v3-adb-prod-meta')
          }
        }
      }

      pipelineJob('DWH_GP/internal_manual/jks-automatic-refresh-mv') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-automatic-refresh-mv.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

      pipelineJob('DWH_GP/manual/jks-multithread-load-hub') {
        parameters {
          choiceParam('namespace', ['', 'dev', 'prod'], 'Выбор кластера для работы')
          choiceParam('dbtype', ['', 'adb', 'template', 'stand'], 'Выбор типа БД.')
          stringParam('dbname', '', 'Название БД для стендов.')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-multithread-load-hub.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

      pipelineJob('DWH_GP/manual/2.Conflog/jks-automatic-deploy-help-platform') {
        parameters {
          choiceParam('branchName', ['prodlog','devlog'], 'Целевая ветка conflog')
          booleanParam('cleanOld', true, 'Очистка неиспользуемого в целевой ветке')
          booleanParam('refactorDB', false, 'Рефакторинг БД')
          booleanParam('runDeployDevlog01', false, 'Запустить автомат раскатки devlog01')
          booleanParam('runDeployDevlog02', false, 'Запустить автомат раскатки devlog02')
          booleanParam('runDeployProdlog', true, 'Запустить автомат раскатки prodlog')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-automatic-deploy-help-platform.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }

      pipelineJob('DWH_GP/manual/2.Conflog/jks-automatic-deploy-conflog-prod') {
        parameters {
          stringParam('deploybranch', 'prodlog', 'Имя ветки для применения')
          booleanParam('refactoring', false, 'Режим рефакторинг?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile-deploy-conflog-prod')
          }
        }
      }

      pipelineJob('DWH_GP/internal_manual/jks-dynamic-pxf-prod') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-automatic-pxf.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile-dynamic-pxf-prod')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/jks-do-prm-task-prod') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-do-prm-task.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile-jks-do-prm-task-prod')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/jks-generate-roles-on-adb-prod') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks_greenplum.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfiles/Jenkinsfile-generate-roles-on-adb-prod')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/jks-automatic-s2t-to-xlsx-prod') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-s2t-to-xlsx.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile-get-data-from-database')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/jks-automatic-bdv-to-xlsx-prod') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-s2t-to-xlsx.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile-get-data-from-database_bdv_logic')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/jks-automatic-generate-and-deploy-detail-dags_PROD') {
        parameters {
          booleanParam('unpauseDags', false, 'Снимать даги с паузы после деплоя?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-automatic-generate-and-deploy-detail-dags.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('PROD/Jenkinsfile')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/automatic-bdv-v3-adb-prod-META') {
        parameters {
          booleanParam('deployDags', true, 'Задеплоить даги на AF prod')
          booleanParam('unpauseDags', false, 'Снимать даги с паузы после деплоя?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('pipelines-prod/Jenkinsfile-automatic-bdv-v3-adb-prod-meta')
          }
        }
      }

      pipelineJob('DWH_GP/internal_manual/jks-automatic-airflow-pausedDags-master') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks_airflow.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile_pausedDags')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/jks-automatic-airflow_varsDagsDeploy_master') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks_airflow.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile_varsDagsDeploy')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/automatic-bdv-v3-adb-prod-DEPLOY_DAG') {
        parameters {
          booleanParam('unpauseDags', false, 'Снимать даги с паузы после деплоя?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks_airflow.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile_adb-prod-deploy-dag-bdv-v3')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/Generate_src_upload_Dags_PROD') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-automatic-generate-and-deploy-detail-dags.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('SRC-UPLOAD/PROD/Jenkinsfile')
          }
        }
      }
