jenkins:
  systemMessage: "Jenkins настроен через Configuration as Code"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false
  scriptApproval:
      approvedSignatures:
        - "method org.jenkinsci.plugins.workflow.support.actions.EnvironmentAction getEnvironment"

  # securityRealm:
  #   local:
  #     allowsSignup: false
  #     users:
  #       - id: "admin"
  #         password: "admin-password"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "cdjksnd"
              username: "cdjks_user"
              password: "jkspass123"
              description: "Учетка для доступа к GitLab"
          - usernamePassword:
              scope: GLOBAL
              id: "adb-prod-admin"
              username: "adb_deploy_cdjks"
              password: "PaswdQ802"
              description: "Учетка для доступа к ADB"

jobs:
  - script: |
      folder('DWH_GP') {}
      folder('DWH_GP/internal_manual') {}

      pipelineJob('DWH_GP/internal_manual/jks-automatic-all-adb-prod') {
        parameters {
          booleanParam('forceterminate', false, 'Принудительно разорвать все сессии к БД ?')
          booleanParam('hotfix', false, 'Режим Hot Fix?')
          booleanParam('refactoring', false, 'Режим рефакторинг?')
          booleanParam('manualpause', false, 'Ручная пауза дагов')
          booleanParam('doUnpaused', true, 'Снимать даги с паузы после раскатки мастера ? (отключать только в экстренных случаях)')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('pipelines-prod/Jenkinsfile-all-adb-prod')
          }
        }
      }

      pipelineJob('DWH_GP/internal_manual/jks-automatic-deploy-adb-prod') {
        parameters {
          booleanParam('hotfix', false, 'Режим Hot Fix?')
          booleanParam('refactoring', false, 'Режим рефакторинг?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('pipelines-prod/Jenkinsfile-deploy-adb-prod')
          }
        }
      }

      pipelineJob('DWH_GP/manual/6.ADB_PROD/automatic-bdv-v3-adb-prod-META') {
        parameters {
          booleanParam('deployDags', true, 'Задеплоить даги на AF prod')
          booleanParam('unpauseDags', false, 'Снимать даги с паузы после деплоя?')
        }
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-liquibase-all.git')
                  credentials('cdjksnd')
                }
                branches('*/master')
              }
            }
            scriptPath('pipelines-prod/Jenkinsfile-automatic-bdv-v3-adb-prod-meta')
          }
        }
      }
