# Этот файл используется для создания кластера Greenplum
# с конфигурацией в отдельных контейнерах на отдельных хостах:
# 1 master - mdw-хост
# 2 primary сегменты без зеркал (sdw*-хосты)

services:
  master:
    image: ${IMAGE_NAME}:${TAG}
    container_name: master
    hostname: master
    ports:
      - "${EXPOSE_MASTER_PORT}:5432"
    environment:
      - GREENPLUM_PXF_BASE_DIRECTORY=/var/lib/pxf
      - GREENPLUM_DEPLOYMENT=singlenode
      - GREENPLUM_START_DEBUG=true
      - GREENPLUM_GPPERFMON_ENABLE=true
      - GREENPLUM_DISKQUOTA_ENABLE=true
      - GREENPLUM_PXF_ENABLE=true
      - GREENPLUM_PASSWORD_FILE=/run/secrets/gpdb_password
      - GREENPLUM_GPMON_PASSWORD_FILE=/run/secrets/gpmon_password
    secrets:
      - gpdb_password
      - gpmon_password
    volumes:
      - gpdb-master-data:/data
      # - ../docs/custom_init_scripts:/docker-entrypoint-initdb.d
      - ./conf/${CONFIG_FOLDER}/gpinitsystem_config_singlenode:/tmp/gpinitsystem_config
      - ./conf/hostlist_singlenode:/tmp/hostfile_gpinitsystem
      - ./conf/pxf:/tmp/pxf
      - ./conf/ssh/id_rsa:/home/gpadmin/.ssh/id_rsa
      - ./conf/ssh/id_rsa.pub:/home/gpadmin/.ssh/id_rsa.pub
    networks:
      - dwh

  external-postgres:
    image: ${POSTGRES_IMAGE_NAME}:${POSTGRES_TAG}
    container_name: external-postgres
    hostname: external-postgres
    environment:
      - POSTGRES_PASSWORD=/run/secrets/postgres_password
    volumes:
      - pgdb-conflog-data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_POSTGRES_PORT}:5432"

networks:
  dwh:

volumes:
  gpdb-master-data:
  pgdb-conflog-data:

secrets:
  gpdb_password:
    file: ./secrets/gpdb_password
  gpmon_password:
    file: ./secrets/gpmon_password
  postgres_password:
    file: ./secrets/postgres_password
