services:
  webdav-ntlm:
    # build: .
    image: dwh/webdav-ntlm:0.0.8-alpine
    container_name: webdav_ntlm_server
    ports:
      - "80:80"
    environment:
      - NTLM_USER=cdjks_s2t
      - NTLM_PASSWORD=password  # Задайте ваш пароль
    volumes:
      # - ./webdav-ntlm.conf:/etc/apache2/sites-enabled/000-default.conf:ro
      # - ./conf:/etc/apache2/sites-enabled:ro
      # - ./shared_excel_files:/var/www/webdav
      - webdav-ntlm:/var/www/webdav
    # restart: always

  # samba-share:
  #   image: dperson/samba
  #   container_name: samba_server
  #   ports:
  #     - "139:139"
  #     - "445:445"
  #   volumes:
  #     - ./shared_excel_files:/mnt/share
  #   command: >
  #     -u "cdjks_s2t;SecretWindowsPassword123" 
  #     -s "excel_share;/mnt/share;no;no;no;cdjks_s2t"
  #     -g "force user = www-data"
  #     -g "force group = www-data"
  #   restart: always
  #   depends_on:
  #     - webdav-ntlm

  samba-share:
    image: dockurr/samba:4.23.8
    container_name: samba_server
    ports:
      - "445:445"
    environment:
      # --- ШАРА 1: Общая папка для Jenkins и Аналитиков ---
      - NAME1=shared_reports
      - USER1=cdjks_s2t
      - PASS1=password
      # - USER2=analyst_user
      # - PASS2=password_analyst

      # --- ШАРА 2: Приватная папка только для Менеджеров ---
      # (Jenkins и аналитики сюда зайти не смогут)
      # - NAME2=managers_private
      # - USER3=manager_user
      # - PASS3=password_manager

      # --- Пользователь apache для доступа из webdav-ntlm
      - UID=82
      - GID=82
    volumes:
      # Важно: монтируем папки из volume в соответствующие подкаталоги /storage
      - webdav-ntlm:/storage/shared_reports
      # - managers-data:/storage/managers_private
    # restart: always

volumes:
  webdav-ntlm:
  # managers-data:
