version: "3.9"

services:
  server:
    image: debian:12-slim
    container_name: ssh-server
    hostname: ssh-server
    volumes:
      - ssh-share:/shared-ssh
      - ./ssh:/init-ssh
    command: ["/bin/bash", "-c", "/init-ssh/server-init.sh && sleep infinity"]
    networks:
      - test-net

  client:
    image: debian:12-slim
    container_name: ssh-client
    hostname: ssh-client
    volumes:
      - ssh-share:/shared-ssh
      - ./ssh:/init-ssh
    command: ["/bin/bash", "-c", "/init-ssh/client-init.sh && sleep infinity"]
    networks:
      - test-net

volumes:
  ssh-share:

networks:
  test-net:
    driver: bridge
