#!/usr/bin/env bash
set -e
set -a; . /docker-entrypoint-initdb.d/.env; set +a

	# GRANT ALL PRIVILEGES ON DATABASE ${AFPROD_BASE_DB} TO ${AFPROD_BASE_USERNAME};
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${AFPROD_BASE_USERNAME} WITH PASSWORD '${AFPROD_BASE_PASSWORD}';
	CREATE DATABASE ${AFPROD_BASE_DB};
	ALTER DATABASE ${AFPROD_BASE_DB} OWNER TO ${AFPROD_BASE_USERNAME};
EOSQL

	# GRANT ALL PRIVILEGES ON DATABASE ${CONFLOG_DATABASE} TO ${CONFLOG_USERNAME};
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${CONFLOG_USERNAME} WITH SUPERUSER CREATEROLE LOGIN PASSWORD '${CONFLOG_PASSWORD}';
	CREATE DATABASE ${CONFLOG_DATABASE};
	ALTER DATABASE ${CONFLOG_DATABASE} OWNER TO ${CONFLOG_USERNAME};
EOSQL

PGPASSWORD="$CONFLOG_PASSWORD" psql -v ON_ERROR_STOP=1 --username "$CONFLOG_USERNAME" --dbname "$CONFLOG_DATABASE" <<-EOSQL
	CREATE ROLE rl_reader;
	CREATE ROLE rl_owner_db;
	CREATE ROLE rl_lm_worker;
	CREATE ROLE rl_log_worker;
	CREATE ROLE db_prod_log01_all;
	CREATE USER cdjks_prodlog_deploy WITH PASSWORD '${CDJKS_PRODLOG_DEPLOY_PASSWORD}';
	CREATE USER cdjks_dumper WITH PASSWORD '${CDJKS_DUMPER_PASSWORD}';
	CREATE USER svc_dw_kafka_prod WITH PASSWORD '${KAFKA_PASSWORD}';
	CREATE USER srv_prodlog01 WITH PASSWORD '${PXF_PASSWORD}';
	GRANT CREATE ON DATABASE db_prod_log01 TO rl_owner_db;
	GRANT CONNECT ON DATABASE db_prod_log01 TO rl_owner_db;
	GRANT db_prod_log01 TO rl_owner_db;
	GRANT db_prod_log01_all TO svc_dw_kafka_prod;

	GRANT rl_owner_db TO cdjks_prodlog_deploy;
	GRANT rl_reader	TO cdjks_prodlog_deploy;
	GRANT rl_lm_worker TO cdjks_prodlog_deploy;
	GRANT rl_log_worker	TO cdjks_prodlog_deploy;

	GRANT rl_reader	TO cdjks_dumper;

	GRANT rl_reader	TO srv_prodlog01;

	CREATE USER ${AFPROD_SUZ_USERNAME} WITH PASSWORD '${AFPROD_SUZ_PASSWORD}';
	GRANT rl_lm_worker TO ${AFPROD_SUZ_USERNAME};
	GRANT rl_log_worker	TO ${AFPROD_SUZ_USERNAME};

	CREATE SCHEMA adb AUTHORIZATION rl_owner_db;
	GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA adb TO rl_owner_db;
	CREATE SCHEMA liquibase AUTHORIZATION rl_owner_db;
EOSQL

# test_ds
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${DS_USERNAME} WITH SUPERUSER CREATEROLE LOGIN PASSWORD '${DS_PASSWORD}';
	CREATE DATABASE ${DS_DATABASE};
	ALTER DATABASE ${DS_DATABASE} OWNER TO ${DS_USERNAME};
EOSQL

# test_cbas
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${CBAS_USERNAME} WITH SUPERUSER CREATEROLE LOGIN PASSWORD '${CBAS_PASSWORD}';
	CREATE DATABASE ${CBAS_DATABASE};
	ALTER DATABASE ${CBAS_DATABASE} OWNER TO ${CBAS_USERNAME};
EOSQL
