[global]
   # Задаем рабочую группу (можно оставить дефолтную)
   workgroup = WORKGROUP
   # Обязательно указываем режим локальной авторизации
   security = user
   # Разрешаем использование NTLMv2 (важно для winbind)
   server role = standalone server
   
   # Логирование для отладки (поможет, если что-то пойдет не так)
   log file = /var/log/samba/log.%m
   max log size = 50
