DavLockDB "/var/lib/dav/DavLock"

Alias /share "/var/www/webdav"

<Directory "/var/www/webdav">
    Dav On
    Options Indexes FollowSymLinks
    AllowOverride None
    
    # Современный NTLM через системный хелпер ntlm_auth
    AuthType NTLM
    AuthName "Linux WebDAV NTLM Share"
    NTLMAuth on
    NTLMAuthHelper "/usr/bin/ntlm_auth --helper-protocol=squid-2.5-ntlmssp"
    
    Require valid-user
</Directory>
