jenkins:
  systemMessage: "Jenkins настроен через Configuration as Code"
  
  # 1. Создаем учетные данные для GitLab
  # securityRealm:
  #   local:
  #     allowsSignup: false
  #     users:
  #       - id: "admin"
  #         password: "admin-password" # Смените на свой

  credentials:
    system:
      domainCredentials:
        - credentials:
            - usernamePassword:
                scope: GLOBAL
                id: "gitlab-creds-id" # Используйте этот ID ниже в пайплайнах
                username: "cdjks_user"
                password: "jkspass123"
                description: "Учетка для доступа к GitLab"

# 2. Описываем создание пайплайнов через Job DSL
jobs:
  - script: >
      pipelineJob('jks-automation-test-one') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url(${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-test-one.git)
                  credentials('gitlab-creds-id')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile')
          }
        }
      }
      
  - script: >
      pipelineJob('jks-automation-test-two') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url(${GITLAB_DWH_URL}/DWH/ADB/service-projects/automation/jks-test-two.git)
                  credentials('gitlab-creds-id')
                }
                branches('*/master')
              }
            }
            scriptPath('Jenkinsfile-test-two')
          }
        }
      }
